var catData = {
	pr: {
		name: 'Prime Cat',
    origen: 'Captain Marvel Photo',
		temperament: ' ',
		height: ' ',
		length:' ',
		mass: ' ',
    lifespan: ' ',
  },		
  ma: {
		name: 'Maine Coon',
    origen: 'Maine, United States',
		temperament: 'gentle giants',
		height: '10–16 ',
		length:'19 – 40 in',
		mass: '15 – 25 lbs',
    lifespan: '13 or 14 years ',		
	},
	br: {
    name: 'British Shorthair',
		origen: 'Great Britain',
		temperament: 'loyal, loving ',
		height:  '12 - 14 in',
		length: '22 - 25 in',
		mass: '7 - 17 lbs ',
    lifespan: '14–20 years ',
	},
	tu: {
    name: 'Turkish Angora',
		origen: 'Turkey',
		temperament: 'affectionate',
		height: '9 to 14 in',
		length: '14 - 17 in',
		mass: '8 to 15 lbs',
	  lifespan: '9 to 14 years',
	},
	be: {
		name: 'Bengal',
		origen: 'United States',
	  temperament: 'energetic and playful',
		height: '9 to 14 in',
		length: '14 - 18 in',
		mass: '8 to 15 lbs',
	  lifespan: '12 to 16 years',
	},
	ly: {
		name: 'lynx',
		origen: 'Canada',
	  temperament: 'wild',
	  height: ' 13-16 in',
		length: '30 - 42 in',
		mass: '18 – 24 lbs',
	  lifespan: '14 to 26 years',
		
	},
	pa: {
		name: 'Pallas',
		origen: 'Mongolia',
	  temperament: 'independent',
	  height: '12 - 14 in',
		length: '18 - 25.5 in',
		mass: '6 - 10 lbs',
	  lifespan: '12 years',		
	},
};